# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login  
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          file: ~/Devops/Iniciativa-Devops/Aula04/kube-news/src/Dockerfile
          context: ~/Devops/Iniciativa-Devops/Aula04/kube-news/src
          push: true
          tags: |
            arisonmota/kube-news:latest
            arisonmota/kube-news:${{github.run_number}}
      
